stages:
  - release
  - deploy

release:
  stage: release
  image: docker:latest
  only:
    - "master"
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
  before_script:
    - "docker version"
    - "docker info"
    - "docker login -u $CI_REGISTRY_USER -p $GITLAB_PERSONAL_TOKEN $CI_REGISTRY"
  script:
    # - echo "pass"
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest -f .docker/Dockerfile ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  after_script:
    - "docker logout ${CI_REGISTRY}"
  tags:
    - nusantara-digital

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - "master"
  services:
    - docker:dind
  before_script:
    - apk add --update --no-cache openssh sshpass
  script:
    - printf "${ENV}" >> .env
    - cat .env
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "mkdir -p /home/app/absensi-web"
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no .docker/docker-compose.yml ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:/home/app/absensi-web/
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no .env ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:/home/app/absensi-web/
    - sshpass -p "${DEPLOYMENT_SERVER_PASS}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "docker login -u ${CI_REGISTRY_USER} -p ${GITLAB_PERSONAL_TOKEN} ${CI_REGISTRY}; docker compose -f /home/app/absensi-web/docker-compose.yml stop; docker compose -f /home/app/absensi-web/docker-compose.yml rm absensi-web --force; docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest; docker compose -f /home/app/absensi-web/docker-compose.yml up -d"
  tags:
    - nusantara-digital
