services:
  web:
    # build: .
    image: registry.gitlab.com/elefandesign/absensi-web:latest
    container_name: 'absensi-web'
    env_file:
      - .env
    ports:
      - "2010:80"
    volumes:
      - /home/app/absensi-web/uploads:/var/www/public/uploads
    #   - /home/app/absensi-web/storage/framework:/var/www/storage/framework
    #   - /home/app/absensi-web/storage/logs:/var/www/storage/logs
    restart: always
