services:
  web:
    # build: .
    image: akatgelar/ayopemilu:latest
    container_name: 'ayopemilu'
    env_file:
      - .env
    ports:
      - "2030:80"
    volumes:
      - /home/app/ayopemilu/uploads:/var/www/public/uploads
    #   - /home/app/companyprofile-laravel/storage/framework:/var/www/storage/framework
    #   - /home/app/companyprofile-laravel/storage/logs:/var/www/storage/logs
    restart: always
